// Mapping ชื่อฟอนต์ภาษาไทย → รายการไฟล์ทั้งหมดใน Firebase Storage (TK studio/)
module.exports = {
  'ฟอนต์ เป็ดน้อย':   ['TKPetnoi.ttf','TKPetnoiBold.ttf','TKPetnoiThin.ttf'],
  'ฟอนต์ คามิน':      ['TKKamin.ttf','TKKaminBold.ttf','TKKaminThin.ttf'],
  'ฟอนต์ กอหญ้า':     ['TKGorya.ttf','TKGoryaThin.ttf','TKGoryaV2.ttf'],
  'ฟอนต์ ขนมตาล':     ['DSKhanomtan.ttf','DSKhanomtanBold.ttf','DSKhanomtanThin.ttf'],
  'ฟอนต์ บลูวาฬ':     ['TKBluewhale.ttf','TKBluewhaleBold.ttf','TKBluewhaleThin.ttf'],
  'ฟอนต์ ลูกพีช':     ['DSLookpeach.ttf','DSLookpeachBold.ttf','DSLookpeachThin.ttf'],
  'ฟอนต์ พาสต้า':     ['DSPasta.ttf','DSPastaBold.ttf','DSPastaThin.ttf'],
  'ฟอนต์ มะพร้าว':    ['TKMaphrao.ttf','TKMaphraoBold.ttf','TKMaphraoThin.ttf'],
  'ฟอนต์ ม้าเต่อ':    ['DSMatoer.ttf','DSMatoerBold.ttf','DSMatoerThin.ttf'],
  'ฟอนต์ สีชอล์ค':    ['DSOilpastel.ttf','DSOilpastelBold.ttf'],
  'ฟอนต์ หนังสือ':    ['DSNangsue.ttf','DSNangsueBold.ttf','DSNangsueThin.ttf'],
  'ฟอนต์ ไข่หวาน':    ['DSKhaiwan.ttf','DSKhaiwanBold.ttf','DSKhaiwanThin.ttf'],
  'ฟอนต์ กู๊ดเดย์':   ['DSGoodday.ttf','DSGooddayBold.ttf','DSGooddayThin.ttf'],
  'ฟอนต์ อินเตอร์':   ['DSInter.ttf','DSInterBold.ttf','DSInterThin.ttf'],
  'ฟอนต์ แคลคูลัส':   ['DSCalculus.ttf','DSCalculusBold.ttf','DSCalculusThin.ttf'],
  'ฟอนต์ ชาร์ลอตต์':  ['DScharlotte.ttf'],
  'ฟอนต์ นิวเยียร์':  ['DSNewyear.ttf','DSNewyearBold.ttf','DSNewyearThin.ttf'],
  'ฟอนต์ ลานดอกไม้':  ['DSlandokmai.ttf'],
  'ฟอนต์ เชียงใหม่':  ['DSChaingmai.ttf','DSChaingmaiBold.ttf','DSChaingmaiThin.ttf'],
  'ฟอนต์ ก๋วยเตี๋ยว': ['DSNoodle.ttf','DSNoodleBold.ttf','DSNoodleThin.ttf'],
  'ฟอนต์มูจิ':        ['TKMooji.ttf','TKMooji Bold.ttf','TKMoojiV2.ttf'],
  'ฟอนต์ฟองนม':       ['DSfongnom.ttf'],
  'ฟอนต์ขาหมู':       ['DSKhamuu.ttf','DSKhamuuBold.ttf'],
  'ฟอนต์ธานอส':       ['TKThanos.ttf','TKThanosBold.ttf','TKThanosThin.ttf'],
  'ฟอนต์พัดลม':       ['DSpadlom.ttf'],
  'ฟอนต์ภูเขา':       ['DSPhukhao.ttf','DSPhukhaoBold.ttf','DSPhukhaoThin.ttf'],
  'ฟอนต์วีนัส':       ['TKVenus.ttf','TKVenusBold.ttf','TKVenusThin.ttf'],
  'ฟอนต์หมูยอ':       ['DSmooyor.ttf','DSmooyorBold.ttf','DSmooyorThin.ttf'],
  'ฟอนต์เซล่า':       ['TKCayla.ttf','TKCaylaBold.ttf','TKCaylaThin.ttf'],
  'ฟอนต์เอนิส':       ['TKAnis.ttf','TKAnisBold.ttf','TKAnisThin.ttf'],
  'ฟอนต์มัสแตง':      ['DSMustang.ttf','DSMustangBold.ttf','DSMustangThin.ttf'],
  'ฟอนต์หมาล่า':      ['DSMala.ttf','DSMalaBold.ttf','DSMalaThin.ttf'],
  'ฟอนต์หมูบิน':      ['TKMoobin.ttf','TKMoobinBold.ttf','TKMoobinThin.ttf'],
  'ฟอนต์เบเกิล':      ['DSBagel.ttf','DSBagelThin.ttf','DSBagelV2.ttf'],
  'ฟอนต์เวลคัม':      ['DSWelcome.ttf','DSWelcomeBold.ttf','DSWelcomeThin.ttf'],
  'ฟอนต์กะเพรา':      ['DSKaphrao.ttf','DSKaphraoBold.ttf','DSKaphraoThin.ttf'],
  'ฟอนต์บางแสน':      ['DSBangsaen.ttf','DSBangsaenBold.ttf','DSBangsaenThin.ttf'],
  'ฟอนต์มอลทีส':      ['DSMaltese.ttf','DSMalteseBold.ttf'],
  'ฟอนต์มันเนย':      ['DSMascot 2.ttf','DSMascotBold.ttf'],
  'ฟอนต์มาสคอส':      ['DSMascot 2.ttf','DSMascotBold.ttf'],
  'ฟอนต์ราสต้า':      ['TKRasta.ttf','TKRastaBold.ttf'],
  'ฟอนต์ห่อหมก':      ['DSHomok.ttf','DSHomokBold.ttf','DSHomokThin.ttf'],
  'ฟอนต์อันโกะ':      ['DSAn-ko.ttf','DSAn-koBold.ttf','DSAn-koThin.ttf'],
  'ฟอนต์ฮิปปี้':      ['DShippie.ttf'],
  'ฟอนต์ฮ่องกง':      ['RGHongkong.ttf','RGHongkongBold.ttf','RGHongkongThin.ttf'],
  'ฟอนต์เนปจูน':      ['TKNeptune.ttf','TKNeptuneBold.ttf'],
  'ฟอนต์เมนเดล':      ['DSMendel.ttf','DSMendelBold.ttf','DSMendelThin.ttf'],
  'ฟอนต์เมล่อน':      ['DSMelon.ttf','DSMelonBold.ttf','DSMelonThin.ttf'],
  'ฟอนต์เลอแปง':      ['DSLepan.ttf','DSLepanBold.ttf','DSLepanThin.ttf'],
  'ฟอนต์แพตตี้':      ['TKPatty.ttf','TKPattyBold.ttf','TKPattyThin.ttf'],
  'ฟอนต์แอนลีน':      ['TKAnlene.ttf','TKAnleneBold.ttf'],
  'ฟอนต์ของเล่น':     ['DSKhonglen.ttf','DSKhonglenBold.ttf','DSKhonglenThin.ttf'],
  'ฟอนต์ข้าวซอย':     ['TKKhaosoi.ttf','TKKhaosoiBold.ttf','TKKhaosoiThin.ttf'],
  'ฟอนต์ข้าวผัด':     ['TKKhaopad.ttf','TKKhaopadBold.ttf','TKKhaopadThin.ttf'],
  'ฟอนต์ครีมพัฟ':     ['TKCreampuff.ttf','TKCreampuffBold.ttf','TKCreampuffThin.ttf'],
  'ฟอนต์คาราเมล':     ['DSCaramel.ttf','DSCaramelBold.ttf','DSCaramelThin.ttf'],
  'ฟอนต์คาเนเล่':     ['TKCanele.ttf','TKCaneleBold.ttf','TKCaneleThin.ttf'],
  'ฟอนต์ชีสเค้ก':     ['DSCheesecake.ttf','DSCheesecakeBold.ttf','DSCheesecakeThin.ttf'],
  'ฟอนต์ซันเดย์':     ['DSSunday.ttf','DSSundayBold.ttf','DSSundayThin.ttf'],
  'ฟอนต์ซิดนีย์':     ['DSSydney.ttf','DSSydneyBold.ttf','DSSydneyThin.ttf'],
  'ฟอนต์ซินเทีย':     ['DScynthia.ttf'],
  'ฟอนต์ตะเกียบ':     ['DStakeab.ttf','DStakeabBold.ttf','DStakeabThin.ttf'],
  'ฟอนต์บัลเลต์':     ['DSBallet.ttf','DSBalletBold.ttf','DSBalletThin.ttf'],
  'ฟอนต์บ้านบอล':     ['DSBanball.ttf','DSBanballBold.ttf','DSBanballThin.ttf'],
  'ฟอนต์บ้านสวน':     ['DSBansuan.ttf','DSBansuanBold.ttf','DSBansuanThin.ttf'],
  'ฟอนต์ปังเย็น':     ['DSpangyen 2.ttf','DSpangyenBold.ttf','DSpangyenThin.ttf'],
  'ฟอนต์ผักกรอบ':     ['DSpakkrob.ttf','DSpakkrobBold.ttf','DSpakkrobThin.ttf'],
  'ฟอนต์พุดดิ้ง':     ['TKPudding.ttf','TKPuddingBold.ttf','TKPuddingThin.ttf'],
  'ฟอนต์มอร์แกน':     ['DSMorgan.ttf','DSMorganBold.ttf'],
  'ฟอนต์มันม่วง':     ['TKManmuang 2.ttf','TKManmuangBold 2.ttf','TKManmuangThin 2.ttf'],
  'ฟอนต์มัลเฟิล':     ['DSMalfeil.ttf','DSMalfeilV2.ttf'],
  'ฟอนต์มาร์ติน':     ['TKMartin.ttf'],
  'ฟอนต์มาร์เวล':     ['DSMarvel.ttf','DSMarvelBold.ttf','DSMarvelThin.ttf'],
  'ฟอนต์มินาโกะ':     ['DSminako.ttf'],
  'ฟอนต์มิเตอร์':     ['DSMeter.ttf','DSMeterBold.ttf','DSMeterThin.ttf'],
  'ฟอนต์วัยเด็ก':     ['DSwaidek.ttf'],
  'ฟอนต์สเกลาร์':     ['DSScalar.ttf','DSScalarBold.ttf','DSScalarThin.ttf'],
  'ฟอนต์หมอนทอง':     ['DSMonThong.ttf','DSMonThongBold.ttf','DSMonThongThin.ttf'],
  'ฟอนต์หมูกรอบ':     ['DSMookrob.ttf','DSMookrobThin.ttf','DSMookrobV2.ttf'],
  'ฟอนต์หม้อแกง':     ['DSMokaeng.ttf','DSMokaengBold.ttf','DSMokaengThin.ttf'],
  'ฟอนต์เจ้านาย':     ['DSJaonaay.ttf','DSJaonaayBold.ttf','DSJaonaayThin.ttf'],
  'ฟอนต์เท็ดดี้':     ['TKTeddy.ttf','TKTeddyBold.ttf','TKTeddyThin.ttf'],
  'ฟอนต์เมเจอร์':     ['DSmajor.ttf'],
  'ฟอนต์กาลิเลโอ':    ['DSgalileo.ttf'],
  'ฟอนต์คอนเนอร์':    ['TKConnor.ttf','TKConnorBold.ttf','TKConnorThin.ttf'],
  'ฟอนต์คาเทียร์':    ['DScatier.ttf'],
  'ฟอนต์ซัมเมอร์':    ['DSsummer.ttf'],
  'ฟอนต์ดาวเสาร์':    ['DSDaosao.ttf','DSDaosaoBold.ttf','DSDaosaoThin.ttf'],
  'ฟอนต์ธันเดอร์':    ['DSThunder.ttf','DSThunderBold.ttf','DSThunderThin.ttf'],
  'ฟอนต์ฟิกเกอร์':    ['DSfigure.ttf'],
  'ฟอนต์มัสตาร์ด':    ['DSMustard.ttf','DSMustardBold.ttf','DSMustardThin.ttf'],
  'ฟอนต์สเปซบาร์':    ['DSSpacebar.ttf','DSSpacebarBold.ttf','DSSpacebarThin.ttf'],
  'ฟอนต์อัลมอนด์':    ['DSAlmond.ttf','DSAlmondBold.ttf','DSAlmondThin.ttf'],
  'ฟอนต์เมอร์ลิน':    ['DSMerlin.ttf','DSMerlinBold.ttf'],
  'ฟอนต์เมืองจีน':    ['DSMueangjeen.ttf','DSMueangjeenBold.ttf','DSMueangjeenThin.ttf'],
  'ฟอนต์ข้าวกล่อง':   ['DSkhaoklong.ttf'],
  'ฟอนต์เมลเบิร์น':   ['DSMelbourne.ttf','DSMelbourneBold.ttf','DSMelbourneThin.ttf'],
  'ฟอนต์เรนเดียร์':   ['DSReindeer.ttf','DSReindeerBold.ttf','DSReindeerThin.ttf'],
  'ฟอนต์เวนส์เดย์':   ['DSWednesday.ttf','DSWednesdayBold.ttf','DSWednesdayThin.ttf'],
  'ฟอนต์แผ่นฟิล์ม':   ['DSpanfilm 3.ttf'],
  'ฟอนต์นิวเคลียร์':  ['DSNewclear.ttf','DSNewclearBold.ttf','DSNewclearThin.ttf'],
  'ฟอนต์เบิร์ดเดย์':  ['DSBirthday.ttf','DSBirthdayBold.ttf','DSBirthdayThin.ttf'],
  'ฟอนต์ฮอว์กินส์':   ['DSHawkins.ttf'],
  'ฟอนต์สังขยา':      ['TKSangkhaya.ttf'],
  'ฟอนต์คัลเจอร์':    ['TKCulture.ttf'],
  'SET:อิโมจิ':       ['DSEmoji01.ttf','DSEmojiEp.2.ttf','EmojiEp3.ttf','DSEmojiEp4.ttf','DSEmojiEp5 2.ttf','DSEmojiEp6.ttf','TKEmojiEp7.ttf','TKEmojiEp8.ttf','DSEmojiEp9.ttf'],
  'ฟอนต์อิโมจิEp.1':  ['DSEmoji01.ttf'],
  'ฟอนต์อิโมจิEp.2':  ['DSEmojiEp.2.ttf'],
  'ฟอนต์อิโมจิEp.3':  ['EmojiEp3.ttf'],
  'ฟอนต์อิโมจิEp.4':  ['DSEmojiEp4.ttf'],
  'ฟอนต์อิโมจิEp.5':  ['DSEmojiEp5 2.ttf'],
  'ฟอนต์อิโมจิEp.6':  ['DSEmojiEp6.ttf'],
  'ฟอนต์อิโมจิEp.7':  ['TKEmojiEp7.ttf'],
  'ฟอนต์อิโมจิEp.8':  ['TKEmojiEp8.ttf'],
  'ฟอนต์อิโมจิEp.9':  ['DSEmojiEp9.ttf'],
  'กล้วยทอด':         ['DSKluai-thot.ttf','DSKluai-thotBold.ttf','DSKluai-thotThin.ttf'],
  'หมูเจียว':         ['TKMoojeaw.ttf','TKMoojeawBold.ttf','TKMoojeawThin.ttf'],
  'ฟอนต์กาเนส':       ['DSGanesh.ttf','DSGaneshBold.ttf'],
  'ฟอนต์แครอท':       ['DSCarrot.ttf','DSCarrotBold.ttf','DSCarrotThin.ttf'],
  'ฟอนต์บัวลอย':      ['DSBualoy.ttf','DSBualoyBold.ttf','DSBualoyThin.ttf'],
  'ฟอนต์ไซโคลน':      ['DScyclone.ttf'],
  'ฟอนต์เมเปิล':      ['DSmaple.ttf'],
  'ฟอนต์ไดอาน่า':     ['DSdiana.ttf','DSdianaBold.ttf'],
  'ฟอนต์ปีเตอร์':     ['TKPeter.ttf','TKPeterThin.ttf','TKPeterV2.ttf'],
  'ฟอนต์สตีเวีย':     ['DSstevia.ttf'],
  'ฟอนต์เอแคลร์':     ['DSEclairs.ttf','DSEclairsBold.ttf','DSEclairsThin.ttf'],
  'ฟอนต์ซับเวย์':     ['DSSubway.ttf','DSSubwayBold.ttf','DSSubwayThin.ttf'],
  'ฟอนต์ดราก้อน':     ['TKDragon.ttf','TKDragonBold.ttf','TKDragonV2.ttf'],
  'ฟอนต์บ็อบเทล':     ['TKBobtail.ttf','TKBobtailBold.ttf','TKBobtailThin.ttf','TKBobtailV2.ttf'],
  'ฟอนต์มอเตอร์':     ['DSMotor.ttf','DSMotorBold.ttf','DSMotorThin.ttf'],
  'ฟอนต์ส้มหวาน':     ['DSSomwhan.ttf','DSSomwhanBold.ttf','DSSomwhanThin.ttf'],
  'ฟอนต์หมูเด้ง':     ['TKMooDeng.ttf','TKMooDengBold.ttf','TKMooDengThin.ttf'],
  'ฟอนต์เพลินวาน':    ['DSPhloenWan.ttf','DSPhloenWanThin.ttf','DSPhloenWanV2.ttf'],
  'ฟอนต์ชานมหนึบ':    ['DSChanomnueb.ttf','DSChanomnuebBold.ttf','DSChanomnuebThin.ttf'],
  'ฟอนต์อร่อยมาก':    ['DSAroimak.ttf','DSAroimakBold.ttf','DSAroimakThin.ttf'],
  'ฟอนต์โคเชลล่า':    ['DSCoachella.ttf'],
  'ฟอนต์วาเลนไทน์':   ['DSValentine.ttf','DSValentineBold.ttf','DSValentineThin.ttf'],
};
