// Mapping ชื่อฟอนต์ภาษาไทย → ชื่อไฟล์ใน Firebase Storage (โฟลเดอร์ fonts/)
const FONT_STORAGE_MAP = {
  'ฟอนต์ เป็ดน้อย':   'TKPetnoi.ttf',
  'ฟอนต์ คามิน':      'TKKamin.ttf',
  'ฟอนต์ กอหญ้า':     'TKGorya.ttf',
  'ฟอนต์ ขนมตาล':     'DSKhanomtan.ttf',
  'ฟอนต์ บลูวาฬ':     'TKBluewhale.ttf',
  'ฟอนต์ ลูกพีช':     'DSLookpeach.ttf',
  'ฟอนต์ พาสต้า':     'DSPasta.ttf',
  'ฟอนต์ มะพร้าว':    'TKMaphrao.ttf',
  'ฟอนต์ ม้าเต่อ':    'DSMatoer.ttf',
  'ฟอนต์ สีชอล์ค':    'DSOilpastel.ttf',
  'ฟอนต์ หนังสือ':    'DSNangsue.ttf',
  'ฟอนต์ ไข่หวาน':    'DSKhaiwan.ttf',
  'ฟอนต์ กู๊ดเดย์':   'DSGoodday.ttf',
  'ฟอนต์ อินเตอร์':   'DSInter.ttf',
  'ฟอนต์ แคลคูลัส':   'DSCalculus.ttf',
  'ฟอนต์ ชาร์ลอตต์':  'DScharlotte.ttf',
  'ฟอนต์ นิวเยียร์':  'DSNewyear.ttf',
  'ฟอนต์ ลานดอกไม้':  'DSlandokmai.ttf',
  'ฟอนต์ เชียงใหม่':  'DSChaingmai.ttf',
  'ฟอนต์ ก๋วยเตี๋ยว': 'DSNoodle.ttf',
  'ฟอนต์มูจิ':        'TKMooji.ttf',
  'ฟอนต์ฟองนม':       'DSfongnom.ttf',
  'ฟอนต์ขาหมู':       'DSKhamuu.ttf',
  'ฟอนต์ธานอส':       'TKThanos.ttf',
  'ฟอนต์พัดลม':       'DSpadlom.ttf',
  'ฟอนต์ภูเขา':       'DSPhukhao.ttf',
  'ฟอนต์วีนัส':       'TKVenus.ttf',
  'ฟอนต์หมูยอ':       'DSmooyor.ttf',
  'ฟอนต์เซล่า':       'TKCayla.ttf',
  'ฟอนต์เอนิส':       'TKAnis.ttf',
  'ฟอนต์มัสแตง':      'DSMustang.ttf',
  'ฟอนต์หมาล่า':      'DSMala.ttf',
  'ฟอนต์หมูบิน':      'TKMoobin.ttf',
  'ฟอนต์เบเกิล':      'DSBagel.ttf',
  'ฟอนต์เวลคัม':      'DSWelcome.ttf',
  'ฟอนต์กะเพรา':      'DSKaphrao.ttf',
  'ฟอนต์บางแสน':      'DSBangsaen.ttf',
  'ฟอนต์มอลทีส':      'DSMaltese.ttf',
  'ฟอนต์มันเนย':      'DSMascot 2.ttf',
  'ฟอนต์มาสคอส':      'DSMascot 2.ttf',
  'ฟอนต์ราสต้า':      'TKRasta.ttf',
  'ฟอนต์ห่อหมก':      'DSHomok.ttf',
  'ฟอนต์อันโกะ':      'DSAn-ko.ttf',
  'ฟอนต์ฮิปปี้':      'DShippie.ttf',
  'ฟอนต์ฮ่องกง':      'RGHongkong.ttf',
  'ฟอนต์เนปจูน':      'TKNeptune.ttf',
  'ฟอนต์เมนเดล':      'DSMendel.ttf',
  'ฟอนต์เมล่อน':      'DSMelon.ttf',
  'ฟอนต์เลอแปง':      'DSLepan.ttf',
  'ฟอนต์แพตตี้':      'TKPatty.ttf',
  'ฟอนต์แอนลีน':      'TKAnlene.ttf',
  'ฟอนต์ของเล่น':     'DSKhonglen.ttf',
  'ฟอนต์ข้าวซอย':     'TKKhaosoi.ttf',
  'ฟอนต์ข้าวผัด':     'TKKhaopad.ttf',
  'ฟอนต์ครีมพัฟ':     'TKCreampuff.ttf',
  'ฟอนต์คาราเมล':     'DSCaramel.ttf',
  'ฟอนต์คาเนเล่':     'TKCanele.ttf',
  'ฟอนต์ชีสเค้ก':     'DSCheesecake.ttf',
  'ฟอนต์ซันเดย์':     'DSSunday.ttf',
  'ฟอนต์ซิดนีย์':     'DSSydney.ttf',
  'ฟอนต์ซินเทีย':     'DScynthia.ttf',
  'ฟอนต์ตะเกียบ':     'DStakeab.ttf',
  'ฟอนต์บัลเลต์':     'DSBallet.ttf',
  'ฟอนต์บ้านบอล':     'DSBanball.ttf',
  'ฟอนต์บ้านสวน':     'DSBansuan.ttf',
  'ฟอนต์ปังเย็น':     'DSpangyen 2.ttf',
  'ฟอนต์ผักกรอบ':     'DSpakkrob.ttf',
  'ฟอนต์พุดดิ้ง':     'TKPudding.ttf',
  'ฟอนต์มอร์แกน':     'DSMorgan.ttf',
  'ฟอนต์มันม่วง':     'TKManmuang 2.ttf',
  'ฟอนต์มัลเฟิล':     'DSMalfeil.ttf',
  'ฟอนต์มาร์ติน':     'TKMartin.ttf',
  'ฟอนต์มาร์เวล':     'DSMarvel.ttf',
  'ฟอนต์มินาโกะ':     'DSminako.ttf',
  'ฟอนต์มิเตอร์':     'DSMeter.ttf',
  'ฟอนต์วัยเด็ก':     'DSwaidek.ttf',
  'ฟอนต์สเกลาร์':     'DSScalar.ttf',
  'ฟอนต์หมอนทอง':     'DSMonThong.ttf',
  'ฟอนต์หมูกรอบ':     'DSMookrob.ttf',
  'ฟอนต์หม้อแกง':     'DSMokaeng.ttf',
  'ฟอนต์เจ้านาย':     'DSJaonaay.ttf',
  'ฟอนต์เท็ดดี้':     'TKTeddy.ttf',
  'ฟอนต์เมเจอร์':     'DSmajor.ttf',
  'ฟอนต์กาลิเลโอ':    'DSgalileo.ttf',
  'ฟอนต์คอนเนอร์':    'TKConnor.ttf',
  'ฟอนต์คาเทียร์':    'DScatier.ttf',
  'ฟอนต์ซัมเมอร์':    'DSsummer.ttf',
  'ฟอนต์ดาวเสาร์':    'DSDaosao.ttf',
  'ฟอนต์ธันเดอร์':    'DSThunder.ttf',
  'ฟอนต์ฟิกเกอร์':    'DSfigure.ttf',
  'ฟอนต์มัสตาร์ด':    'DSMustard.ttf',
  'ฟอนต์สเปซบาร์':    'DSSpacebar.ttf',
  'ฟอนต์อัลมอนด์':    'DSAlmond.ttf',
  'ฟอนต์เมอร์ลิน':    'DSMerlin.ttf',
  'ฟอนต์เมืองจีน':    'DSMueangjeen.ttf',
  'ฟอนต์ข้าวกล่อง':   'DSkhaoklong.ttf',
  'ฟอนต์เมลเบิร์น':   'DSMelbourne.ttf',
  'ฟอนต์เรนเดียร์':   'DSReindeer.ttf',
  'ฟอนต์เวนส์เดย์':   'DSWednesday.ttf',
  'ฟอนต์แผ่นฟิล์ม':   'DSpanfilm 3.ttf',
  'ฟอนต์นิวเคลียร์':  'DSNewclear.ttf',
  'ฟอนต์เบิร์ดเดย์':  'DSBirthday.ttf',
  'ฟอนต์อิโมจิEp.1':  'DSEmoji01.ttf',
  'ฟอนต์อิโมจิEp.2':  'DSEmojiEp.2.ttf',
  'ฟอนต์อิโมจิEp.3':  'EmojiEp3.ttf',
  'ฟอนต์อิโมจิEp.4':  'DSEmojiEp4.ttf',
  'ฟอนต์อิโมจิEp.5':  'DSEmojiEp5 2.ttf',
  'ฟอนต์อิโมจิEp.6':  'DSEmojiEp6.ttf',
  'ฟอนต์อิโมจิEp.7':  'TKEmojiEp7.ttf',
  'ฟอนต์อิโมจิEp.8':  'TKEmojiEp8.ttf',
  'ฟอนต์อิโมจิEp.9':  'DSEmojiEp9.ttf',
  'กล้วยทอด':         'DSKluai-thot.ttf',
  'หมูเจียว':         'TKMoojeaw.ttf',
  'ฟอนต์กาเนส':       'DSGanesh.ttf',
  'ฟอนต์แครอท':       'DSCarrot.ttf',
  'ฟอนต์บัวลอย':      'DSBualoy.ttf',
  'ฟอนต์ไซโคลน':      'DScyclone.ttf',
  'ฟอนต์เมเปิล':      'DSmaple.ttf',
  'ฟอนต์ไดอาน่า':     'DSdiana.ttf',
  'ฟอนต์ปีเตอร์':     'TKPeter.ttf',
  'ฟอนต์สตีเวีย':     'DSstevia.ttf',
  'ฟอนต์เอแคลร์':     'DSEclairs.ttf',
  'ฟอนต์ซับเวย์':     'DSSubway.ttf',
  'ฟอนต์ดราก้อน':     'TKDragon.ttf',
  'ฟอนต์บ็อบเทล':     'TKBobtail.ttf',
  'ฟอนต์มอเตอร์':     'DSMotor.ttf',
  'ฟอนต์ส้มหวาน':     'DSSomwhan.ttf',
  'ฟอนต์หมูเด้ง':     'TKMooDeng.ttf',
  'ฟอนต์เพลินวาน':    'DSPhloenWan.ttf',
  'ฟอนต์ชานมหนึบ':    'DSChanomnueb.ttf',
  'ฟอนต์อร่อยมาก':    'DSAroimak.ttf',
  'ฟอนต์โคเชลล่า':    'DSCoachella.ttf',
  'ฟอนต์วาเลนไทน์':   'DSValentine.ttf',
};
